### ISSUE TITLE
Dev branch JSON loading

### ISSUE THREAD

**Issue by ghost** [IBM/stomp#2]
Hello, I'm having some problems on the dev branch that seem to have to do with JSON loading. Could the repo track a requirements.txt file so that I can be sure my environment is correct before posting the specific issue I'm having?

**Comment by ghost** [comment]
Here's the error that I'm getting. The problem seems to be that the input_trace_file is None. If I edit stomp.json or create a different json with a value for input_trace_file, the program still reads it as none. However, if I change the cpu server count, that change is reflected in the configuration output.

When I pass an input trace file as the argument, the program works.

**./stomp_main.py** and **./stomp_main.py --conf-file=stomp.json**
`(IBM-stomp) alhorgan@sdh01:~/IBM/stomp-1$ ./stomp_main.py 
CONFIGURATION:
{u'simulation': {u'stdev_factor': 0.01, u'power_mgmt_enabled': False, u'tasks': {u'cnn_14': {u'mean_service_time': {u'gpu': 52, u'cpu_core': 162, u'accel': 18}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.52, u'cpu_core': 1.62, u'accel': 0.18}, u'power': {u'gpu': 52, u'cpu_core': 162, u'accel': 18}}, u'fft_128': {u'mean_service_time': {u'gpu': 8, u'cpu_core': 83, u'accel': 1}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.08, u'cpu_core': 0.83, u'accel': 0.01}, u'power': {u'gpu': 8, u'cpu_core': 83, u'accel': 1}}, u'fft_256': {u'mean_service_time': {u'gpu': 10, u'cpu_core': 319, u'accel': 1}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.1, u'cpu_core': 3.2, u'accel': 0.01}, u'power': {u'gpu': 10, u'cpu_core': 319, u'accel': 1}}, u'decoder': {u'mean_service_time': {u'gpu': 2, u'cpu_core': 100}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.2, u'cpu_core': 1.0}, u'power': {u'gpu': 2, u'cpu_core': 100}}, u'fft_64': {u'mean_service_time': {u'gpu': 8, u'cpu_core': 9, u'accel': 1}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.08, u'cpu_core': 0.09, u'accel': 0.01}, u'power': {u'gpu': 8, u'cpu_core': 9, u'accel': 1}}, u'cnn_32': {u'mean_service_time': {u'gpu': 35, u'cpu_core': 58, u'accel': 5}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.35, u'cpu_core': 0.58, u'accel': 0.05}, u'power': {u'gpu': 35, u'cpu_core': 58, u'accel': 5}}}, u'sched_policy_module': u'policies.simple_policy_ver1', u'servers': {u'gpu': {u'count': 2}, u'cpu_core': {u'count': 8}, u'accel': {u'count': 1}}, u'max_tasks_simulated': 10000, u'max_queue_size': 1000000, u'mean_arrival_time': 25, u'promote': True, u'arrival_time_scale': 1.0}, u'general': {u'random_seed': 0, u'pre_gen_arrivals': False, u'basename': u'', u'output_trace_file': u'', u'working_dir': u'.', u'input_trace_file': None, u'logging_level': u'INFO'}}


Running STOMP simulation...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/DATA/SDH/packages/anaconda3/envs/IBM-stomp/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/DATA/SDH/packages/anaconda3/envs/IBM-stomp/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alhorgan/IBM/stomp-1/meta.py", line 149, in run
    in_trace_name = self.working_dir + '/' + self.input_trace_file
TypeError: coercing to Unicode: need string or buffer, NoneType found`

**Comment by aporvaa** [comment]
Hi,

I fixed the code to take a default input-trace if none is provided through an input argument. Since the dev branch only supports input trace mode at the moment it was expecting a trace file using the command line option.

**Comment by ghost** [comment]
So, I thought that I could pass a trace file to stomp_main through the JSON configuration file. 

I tried "user_traces/user_gen_trace.trc" for the value of the "input_trace_file" field with the following output:

`(IBM-stomp) alhorgan@sdh01:~/IBM/stomp-1$ ./stomp_main.py --conf-file=stomp-input-trace.json
CONFIGURATION:
{u'simulation': {u'stdev_factor': 0.01, u'power_mgmt_enabled': False, u'tasks': {u'cnn_14': {u'mean_service_time': {u'gpu': 52, u'cpu_core': 162, u'accel': 18}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.52, u'cpu_core': 1.62, u'accel': 0.18}, u'power': {u'gpu': 52, u'cpu_core': 162, u'accel': 18}}, u'fft_128': {u'mean_service_time': {u'gpu': 8, u'cpu_core': 83, u'accel': 1}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.08, u'cpu_core': 0.83, u'accel': 0.01}, u'power': {u'gpu': 8, u'cpu_core': 83, u'accel': 1}}, u'fft_256': {u'mean_service_time': {u'gpu': 10, u'cpu_core': 319, u'accel': 1}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.1, u'cpu_core': 3.2, u'accel': 0.01}, u'power': {u'gpu': 10, u'cpu_core': 319, u'accel': 1}}, u'decoder': {u'mean_service_time': {u'gpu': 2, u'cpu_core': 100}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.2, u'cpu_core': 1.0}, u'power': {u'gpu': 2, u'cpu_core': 100}}, u'fft_64': {u'mean_service_time': {u'gpu': 8, u'cpu_core': 9, u'accel': 1}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.08, u'cpu_core': 0.09, u'accel': 0.01}, u'power': {u'gpu': 8, u'cpu_core': 9, u'accel': 1}}, u'cnn_32': {u'mean_service_time': {u'gpu': 35, u'cpu_core': 58, u'accel': 5}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.35, u'cpu_core': 0.58, u'accel': 0.05}, u'power': {u'gpu': 35, u'cpu_core': 58, u'accel': 5}}}, u'sched_policy_module': u'policies.simple_policy_ver1', u'servers': {u'gpu': {u'count': 2}, u'cpu_core': {u'count': 8}, u'accel': {u'count': 1}}, u'max_tasks_simulated': 10000, u'max_queue_size': 1000000, u'mean_arrival_time': 25, u'promote': True, u'arrival_time_scale': 1.0}, u'general': {u'random_seed': 0, u'pre_gen_arrivals': False, u'basename': u'', u'output_trace_file': u'', u'working_dir': u'.', u'input_trace_file': None, u'logging_level': u'INFO'}}


Running STOMP simulation...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/DATA/SDH/packages/anaconda3/envs/IBM-stomp/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/DATA/SDH/packages/anaconda3/envs/IBM-stomp/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alhorgan/IBM/stomp-1/meta.py", line 149, in run
    in_trace_name = self.working_dir + '/' + self.input_trace_file
TypeError: coercing to Unicode: need string or buffer, NoneType found` 

Is the code ignoring that section of the configuration file or did I misunderstand something?
(I haven't seen your code fix yet, so maybe you addressed this already.)

**Comment by aporvaa** [comment]
Yes, this is fixed in the recent changes. Prev code ignored the input trace section from the json file. It is fixed in the latest commit.
