### ISSUE TITLE
Adding new server to configuration file

### ISSUE THREAD

**Issue by ghost** [IBM/stomp#5]
I get the following output when I try to add a new server called 'abc_server' to the configuration file.

(IBM-stomp) alhorgan@sdh01:~/IBM/stomp-1$ python stomp_main.py --conf-file=stomp_new_server.json 
CONFIGURATION:
{u'simulation': {u'stdev_factor': 0.01, u'power_mgmt_enabled': False, u'tasks': {u'cnn_14': {u'mean_service_time': {u'gpu': 52, u'cpu_core': 162, u'accel': 18, u'abc_server': 12}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.52, u'cpu_core': 1.62, u'accel': 0.18, u'abc_server': 0.2}, u'power': {u'gpu': 2915, u'cpu_core': 864, u'accel': 583, u'abc_server': 600}}, u'fft_128': {u'mean_service_time': {u'gpu': 8, u'cpu_core': 83, u'accel': 1, u'abc_server': 4}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.08, u'cpu_core': 0.83, u'accel': 0.01, u'abc_server': 0.08}, u'power': {u'gpu': 1228, u'cpu_core': 883, u'accel': 246, u'abc_server': 200}}, u'fft_256': {u'mean_service_time': {u'gpu': 10, u'cpu_core': 319, u'accel': 1, u'abc_server': 4}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.1, u'cpu_core': 3.2, u'accel': 0.01, u'abc_server': 0.08}, u'power': {u'gpu': 6364, u'cpu_core': 1036, u'accel': 1273, u'abc_server': 1000}}, u'decoder': {u'mean_service_time': {u'gpu': 2, u'cpu_core': 100}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.2, u'cpu_core': 1.0}, u'power': {u'gpu': 1228, u'cpu_core': 864}}, u'fft_64': {u'mean_service_time': {u'gpu': 8, u'cpu_core': 9, u'accel': 1, u'abc_server': 4}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.08, u'cpu_core': 0.09, u'accel': 0.01, u'abc_server': 0.08}, u'power': {u'gpu': 2533, u'cpu_core': 1132, u'accel': 506, u'abc_server': 400}}, u'cnn_32': {u'mean_service_time': {u'gpu': 35, u'cpu_core': 58, u'accel': 5, u'abc_server': 10}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.35, u'cpu_core': 0.58, u'accel': 0.05, u'abc_server': 0.2}, u'power': {u'gpu': 2225, u'cpu_core': 634, u'accel': 445, u'abc_server': 500}}}, u'sched_policy_module': u'policies.simple_policy_ver1', u'servers': {u'gpu': {u'count': 2}, u'cpu_core': {u'count': 8}, u'accel': {u'count': 1}, u'abc_server': {u'count': 3}}, u'max_tasks_simulated': 10000, u'max_queue_size': 1000000, u'mean_arrival_time': 25, u'promote': True, u'arrival_time_scale': 1.0}, u'general': {u'comment': u'Power values derived from Jetson TX1 dev board. CPU power numbers are scaled to 1/N where N is the number of cores on the TX1. Accel power values are placeholders right now and are set to 1/5th of corresponding GPU power numbers.', u'random_seed': 0, u'pre_gen_arrivals': False, u'basename': u'', u'output_trace_file': u'', u'unit_of_time': u'10^-5s', u'working_dir': u'.', u'input_trace_file': u'user_traces/user_gen_trace.trc', u'unit_of_power': u'mW', u'logging_level': u'INFO'}}

./user_traces/user_gen_trace.trc

Running STOMP simulation...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/DATA/SDH/packages/anaconda3/envs/IBM-stomp/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/DATA/SDH/packages/anaconda3/envs/IBM-stomp/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alhorgan/IBM/stomp-1/stomp.py", line 737, in run
    server = self.sched_policy.assign_task_to_server(self.sim_time, self.tasks)
  File "/home/alhorgan/IBM/stomp-1/policies/simple_policy_ver1.py", line 55, in assign_task_to_server
    server.assign_task(sim_time, tasks.pop(0))
  File "/home/alhorgan/IBM/stomp-1/stomp.py", line 124, in assign_task
    service_time                    = task.per_server_service_dict[self.type] # Use the per-server type service time, indexed by server_type
KeyError: u'abc_server'

**Comment by ghost** [comment]
Btw, this is on the dev branch.

**Comment by aporvaa** [comment]
Fixed it in commit https://github.com/IBM/stomp/commit/6ca8d06c70ecf0c9e5690ba64e39321e8e7a56ca
