### ISSUE TITLE
Creating new DAG graphml file on dev branch

### ISSUE THREAD

**Issue by ghost** [IBM/stomp#6]
I tried creating a new graphml file in inputs that basically has three nodes, each referencing one of the three other graphml files. I called the file "random_dag_5710.graphml". I generated a new trace file, and I receive the following error when I run the simulation:

(IBM-stomp) alhorgan@sdh01:~/IBM/stomp-1$ python stomp_main.py 
CONFIGURATION:
{u'simulation': {u'stdev_factor': 0.01, u'power_mgmt_enabled': False, u'tasks': {u'cnn_14': {u'mean_service_time': {u'gpu': 52, u'cpu_core': 162, u'accel': 18}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.52, u'cpu_core': 1.62, u'accel': 0.18}, u'power': {u'gpu': 2915, u'cpu_core': 864, u'accel': 583}}, u'fft_128': {u'mean_service_time': {u'gpu': 8, u'cpu_core': 83, u'accel': 1}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.08, u'cpu_core': 0.83, u'accel': 0.01}, u'power': {u'gpu': 1228, u'cpu_core': 883, u'accel': 246}}, u'fft_256': {u'mean_service_time': {u'gpu': 10, u'cpu_core': 319, u'accel': 1}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.1, u'cpu_core': 3.2, u'accel': 0.01}, u'power': {u'gpu': 6364, u'cpu_core': 1036, u'accel': 1273}}, u'decoder': {u'mean_service_time': {u'gpu': 2, u'cpu_core': 100}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.2, u'cpu_core': 1.0}, u'power': {u'gpu': 1228, u'cpu_core': 864}}, u'fft_64': {u'mean_service_time': {u'gpu': 8, u'cpu_core': 9, u'accel': 1}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.08, u'cpu_core': 0.09, u'accel': 0.01}, u'power': {u'gpu': 2533, u'cpu_core': 1132, u'accel': 506}}, u'cnn_32': {u'mean_service_time': {u'gpu': 35, u'cpu_core': 58, u'accel': 5}, u'deadline': 1000, u'stdev_service_time': {u'gpu': 0.35, u'cpu_core': 0.58, u'accel': 0.05}, u'power': {u'gpu': 2225, u'cpu_core': 634, u'accel': 445}}}, u'sched_policy_module': u'policies.simple_policy_ver1', u'servers': {u'gpu': {u'count': 2}, u'cpu_core': {u'count': 8}, u'accel': {u'count': 1}}, u'max_tasks_simulated': 10000, u'max_queue_size': 1000000, u'mean_arrival_time': 25, u'promote': True, u'arrival_time_scale': 1.0}, u'general': {u'comment': u'Power values derived from Jetson TX1 dev board. CPU power numbers are scaled to 1/N where N is the number of cores on the TX1. Accel power values are placeholders right now and are set to 1/5th of corresponding GPU power numbers.', u'random_seed': 0, u'pre_gen_arrivals': False, u'basename': u'', u'output_trace_file': u'', u'unit_of_time': u'10^-5s', u'working_dir': u'.', u'input_trace_file': u'user_traces/user_gen_trace.trc', u'unit_of_power': u'mW', u'logging_level': u'INFO'}}

./user_traces/user_gen_trace.trc

Running STOMP simulation...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/DATA/SDH/packages/anaconda3/envs/IBM-stomp/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/DATA/SDH/packages/anaconda3/envs/IBM-stomp/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alhorgan/IBM/stomp-1/meta.py", line 237, in run
    task = the_dag_sched.comp[node.tid][0]
IndexError: list index out of range

**Comment by ghost** [comment]
I'm sorry, the error I posted was from something unrelated. After fixing that error, I renamed the file to "random_dag_22.graphml" and generated new traces, but I get the following error:
IOError: [Errno 2] No such file or directory: 'inputs/random_comp_22_0.01.txt'

Because the DAG is just referencing other graphml files, I'm not sure what to do about the comp file.

**Comment by aporvaa** [comment]
You’ll have to create the comp files as well. It’s a timing profile of each task in the DAG on the servers.
